services:
  - type: web
    name: tathya-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: tathya_db
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_PLAN_ID
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
